version: '3.1'
services:
  easy_id_generator_db1:
    image: 'mysql:5.7'
    container_name: 'easy_id_generator_db1'
    environment:
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_DATABASE=easy-id-generator'
      - 'TZ=UTC'
    restart: 'always'
    ports:
      - '3307:3306'
    volumes:
      - './db1/mysql:/etc/mysql/conf.d'
      - './db1/mysql/data:/var/lib/mysql'
  easy_id_generator_db2:
    image: 'mysql:5.7'
    container_name: 'easy_id_generator_db2'
    environment:
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_DATABASE=easy-id-generator'
      - 'TZ=UTC'
    restart: 'always'
    ports:
      - '3308:3306'
    volumes:
      - './db2/mysql:/etc/mysql/conf.d'
      - './db2/mysql/data:/var/lib/mysql'
  easy_id_generator_zk:
    image: 'zookeeper:3.4.14'
    restart: 'always'
    hostname: 'easy_id_generator_z1'
    container_name: 'easy_id_generator_z1'
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: '1'
    volumes:
      - './easy_id_generator_z1/cfg:/conf'
      - './easy_id_generator_z1/data:/data'
      - './easy_id_generator_z1/datalog:/datalog'